version: 0.1.62-pre{build}

pull_requests:
  do_not_increment_build_number: true

# Skipping commits affecting specific files
skip_commits:
  files:
  - '**\AssemblyInfo.*'
  - '**/*.md'
  - 'LICENSE'
  - dir/*
  - '.gitignore'

branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
clone_depth: 1
install:
- cmd: git submodule update --init --recursive
build_script:
- ps: >-
    nuget restore source\nanoFramework.Tools.VisualStudio.sln

    msbuild source\nanoFramework.Tools.VisualStudio.sln /p:Configuration=Release  /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: '**\*.vsix'
  name: VS_extension
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: nanoFramework VS2017 Extension v$(appveyor_build_version)
  description: add description here
  auth_token:
    secure: DNixoFFE+pGlwyhj7McfZoln42vOmj0iY1iNV9zXEr3y0NpXlOIgL8k5ehzlFM1S
  artifact: VS_extension
  draft: true
  prerelease: true
  force_update: true
- provider: Nuget
  server: https://www.myget.org/F/nanoframework-dev/vsix/
  api_key:
    secure: 0drE56FivPFYI3oVZWcVFTpjOXSqyjT6kGangIxFRcRLqMhV3lQHqUButuuiPM+N
  artifact: VS_extension
notifications:
- provider: Slack
  auth_token:
    secure: 2tqAJTTbN2dm24Vrwo5TXun3Vxc34R5G9l7o3pK3xEuKZAzxx3nbP2yGkMI/kl3+NxHXknjBfZnkhZC5eLYBHb+jO7YVUZwPYOfC/ZGy5HU=
  channel: '#build-monitor'
  on_build_status_changed: true
  on_build_success: false
  on_build_failure: false  
