version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Debug
clone_depth: 1
install:
- cmd: git submodule update --init --recursive
build_script:
- ps: >-
    msbuild source\Tools.MetaDataProcessor\nanoFramework.Tools.MetaDataProcessor.sln /p:Configuration=Release  /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


    nuget restore source\Tools.BuildTasks\Tools.MSBuildSystem.sln


    msbuild source\Tools.BuildTasks\Tools.MSBuildSystem.sln /p:Configuration=Release  /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


    nuget restore source\nanoFramework.Tools.VisualStudio.AppVeyorBuild.sln


    msbuild source\nanoFramework.Tools.VisualStudio.AppVeyorBuild.sln /p:Configuration=Release  /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: '**\bin\Release\*MSBuildSystem*.nupkg'
  name: MSBuild_System_Nuget_Package
- path: '**\*.vsix'
  name: VS_extension
deploy:
- provider: NuGet
  api_key:
    secure: NSRDXbS8tmzOy4wStGuO3yQMKI8Sk10vF8iQtz9ZDXEnHfwnuDdnXbr/Kno3MMvY
  skip_symbols: true
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: nanoFramework VS2017 Extension v$(appveyor_build_version)
  description: add description here
  auth_token:
    secure: DNixoFFE+pGlwyhj7McfZoln42vOmj0iY1iNV9zXEr3y0NpXlOIgL8k5ehzlFM1S
  artifact: VS_extension
  draft: true
  prerelease: true
  force_update: true
